name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  

    - name: Restore dependencies
      run: dotnet restore TestLab1\UnitTest1.cs

    - name: Build
      run: dotnet build TestLab1\UnitTest1.cs

    - name: Run tests
      run: dotnet test TestLab1\UnitTest1.cs
